version: '3.7'

services:

  grafana:
    image: grafana/grafana
    container_name: grafana
    networks:
      - web
    volumes:
      - data_grafana:/var/lib/grafana/dashboards
    ports:
      - 3000:3000
      
  mysql:
    image: mysql:8
    container_name: mysql_grafana
    networks:
      - web
    command: --init-file /data/application/proyecto.sql
    volumes:
      - ./proyecto.sql:/data/application/proyecto.sql
      - mysql_grafana:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=secret
      - MYSQL_USER=laura
      - MYSQL_PASSWORD=test
      - MYSQL_DATABASE=h2olock
    ports:
      - 3307:3306
      
  prom_mysql_exporter:
    image: prom/mysqld-exporter
    links:
      - mysql
    ports:
      - '9104:9104'
    environment:
      DATA_SOURCE_NAME: root:secret@(mysql:3307)/h2olock
    command: /bin/mysqld_exporter collect.binlog_size=true collect.info_schema.processlist=true
    
  prometheus:
    image: prom/prometheus
    volumes:
      - ./prometheus:/etc/prometheus
    links:
      - prom_mysql_exporter
    ports:
      - 9090



volumes:
  data_grafana:
  mysql_grafana:

networks:
  web:
    driver: bridge
